# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHYa6t52oDmPgd--hDOWF5PIG6YQITXc
"""

import pandas as pd

# Read the XLSX file
excel_file = '/content/air.xlsx'
df = pd.read_excel(excel_file)

# Save as CSV
csv_file = '/content/air.csv'
df.to_csv(csv_file, index=False)

print(f"'{excel_file}' successfully converted to '{csv_file}'.")

import pandas as pd

# Load your data (example)
# df = pd.read_csv("data.csv")

# Convert columns to datetime
df['from'] = pd.to_datetime(df['from'])
df['to'] = pd.to_datetime(df['to'])

# -----------------------------
# Column 1 → Day (Sun, Mon...)
# -----------------------------
df['day'] = df['from'].dt.day_name().str[:3]

# -----------------------------
# Column 2 → Time Category
# -----------------------------
def time_category(dt):
    hour = dt.hour
    if 5 <= hour < 12:
        return "Mrng"
    elif 12 <= hour < 17:
        return "Noon"
    else:
        return "Evng"

df['time_category'] = df['to'].apply(time_category)

# View result
print(df[['from', 'day', 'to', 'time_category']].head())

# Remove 'from' and 'to' columns
df.drop(columns=['from', 'to'], inplace=True)

# Check result
print(df.head())

df.drop(columns=['case', 'day type'], inplace=True)

# Check result
print(df.head())

df.rename(columns={'time_category': 'time'}, inplace=True)

print(df.head())

# -----------------------------
# Encode day (Sun=0 ... Sat=6)
# -----------------------------
day_map = {
    'Sun': 0,
    'Mon': 1,
    'Tue': 2,
    'Wed': 3,
    'Thu': 4,
    'Fri': 5,
    'Sat': 6
}
df['day'] = df['day'].map(day_map)

# -----------------------------
# Encode place
# -----------------------------
place_map = {
    'canteen': 0,
    'parking': 1,
    'class': 2
}
df['place'] = df['place'].map(place_map)

# -----------------------------
# Encode time
# -----------------------------
time_map = {
    'Mrng': 0,
    'Noon': 1,
    'Evng': 2
}
df['time'] = df['time'].map(time_map)

# Check result
print(df.head())

df = df.sort_values(['day', 'time'])

X_context = df[['place', 'day', 'time']].values
Y_targets = df[['co_ppm','hum','mq7_raw','pm1','pm10','pm25','temp']].values

import numpy as np

SEQ_LEN = 5  # academic-friendly

X_lstm = []
Y_lstm = []

for i in range(len(Y_targets) - SEQ_LEN):
    X_lstm.append(Y_targets[i:i+SEQ_LEN])
    Y_lstm.append(Y_targets[i+SEQ_LEN])

X_lstm = np.array(X_lstm)
Y_lstm = np.array(Y_lstm)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

lstm_model = Sequential([
    LSTM(64, input_shape=(SEQ_LEN, 7), return_sequences=False),
    Dense(32, activation='relu'),
    Dense(7)
])

lstm_model.compile(optimizer='adam', loss='mse')
lstm_model.fit(X_lstm, Y_lstm, epochs=30, batch_size=16)

lstm_features = lstm_model.predict(X_lstm)

X_hybrid = np.hstack([
    lstm_features,
    X_context[SEQ_LEN:]
])

from xgboost import XGBRegressor
from sklearn.multioutput import MultiOutputRegressor

xgb = MultiOutputRegressor(
    XGBRegressor(
        n_estimators=200,
        learning_rate=0.05,
        max_depth=4
    )
)

xgb.fit(X_hybrid, Y_lstm)

# place, day, time
# Example: canteen=0, Thu=4, Mrng=0
test_context = np.array([[0, 4, 0]])

# Last 5 timesteps of sensor readings (example values)
test_sequence = np.array([
    [3.16228, 32, 10, 120, 3900, 65, 33.5],
    [5.23832, 33, 14, 125, 2950, 70, 33.7],
    [3.64829, 32, 11, 133, 3024, 71, 33.9],
    [5.809477, 34, 15, 140, 3387, 69, 34.1],
    [6.43168, 35, 17, 145, 3287, 68, 34.3]
])

# Reshape for LSTM
test_sequence = test_sequence.reshape(1, SEQ_LEN, 7)

lstm_out = lstm_model.predict(test_sequence)

hybrid_input = np.hstack([lstm_out, test_context])

final_prediction = xgb.predict(hybrid_input)

sensor_names = [
    'co_ppm', 'hum', 'mq7_raw',
    'pm1', 'pm10', 'pm25', 'temp'
]

for name, value in zip(sensor_names, final_prediction[0]):
    print(f"{name}: {value:.2f}")

import numpy as np

# =====================================================
# 1. USER INPUT (HUMAN READABLE)
# =====================================================
input_day = "Thu"        # Sun, Mon, Tue, Wed, Thu, Fri, Sat
input_place = "Canteen"  # Canteen, Parking, Class
input_time = "Noon"      # Mrng, Noon, Evng

# Last SEQ_LEN sensor readings (example / buffer)
last_sensor_readings = [
    [3.16228, 32, 10, 120, 3900, 65, 33.5],
    [5.23832, 33, 14, 125, 2950, 70, 33.7],
    [3.64829, 32, 11, 133, 3024, 71, 33.9],
    [5.809477, 34, 15, 140, 3387, 69, 34.1],
    [6.43168, 35, 17, 145, 3287, 68, 34.3]
]

# =====================================================
# 2. ENCODING MAPS
# =====================================================
day_map = {
    'Sun': 0, 'Mon': 1, 'Tue': 2,
    'Wed': 3, 'Thu': 4, 'Fri': 5, 'Sat': 6
}

place_map = {
    'Canteen': 0,
    'Parking': 1,
    'Class': 2
}

time_map = {
    'Mrng': 0,
    'Noon': 1,
    'Evng': 2
}

# Encode inputs
day_enc = day_map[input_day]
place_enc = place_map[input_place]
time_enc = time_map[input_time]

context_input = np.array([[place_enc, day_enc, time_enc]])

# =====================================================
# 3. LSTM PREDICTION
# =====================================================
lstm_input = np.array(last_sensor_readings).reshape(1, SEQ_LEN, 7)
lstm_features = lstm_model.predict(lstm_input)

# =====================================================
# 4. HYBRID INPUT → XGBOOST
# =====================================================
hybrid_input = np.hstack([lstm_features, context_input])
final_prediction = xgb.predict(hybrid_input)

# =====================================================
# 5. DISPLAY OUTPUT
# =====================================================
sensor_names = [
    'co_ppm', 'hum', 'mq7_raw',
    'pm1', 'pm10', 'pm25', 'temp'
]

print("\nPredicted Environmental Values:\n")
for name, value in zip(sensor_names, final_prediction[0]):
    print(f"{name:8s}: {value:.2f}")

# ================================
# SAVE LSTM MODEL (.h5)
# ================================
lstm_model.save("lstm_model.h5")
print("LSTM model saved as lstm_model.h5")

# ================================
# SAVE XGBOOST MODEL
# ================================
import joblib

joblib.dump(xgb, "xgboost_model.pkl")
print("XGBoost model saved as xgboost_model.pkl")

import numpy as np
import joblib
from tensorflow.keras.models import load_model

# ================================
# LOAD MODELS (FIXED)
# ================================
lstm_model = load_model("lstm_model.h5", compile=False)
xgb = joblib.load("xgboost_model.pkl")

SEQ_LEN = 5

# ================================
# USER INPUT
# ================================
input_day = "Thu"
input_place = "Canteen"
input_time = "Mrng"

last_sensor_readings = [
    [3.16228, 32, 10, 120, 3900, 65, 33.5],
    [5.23832, 33, 14, 125, 2950, 70, 33.7],
    [3.64829, 32, 11, 133, 3024, 71, 33.9],
    [5.809477, 34, 15, 140, 3387, 69, 34.1],
    [6.43168, 35, 17, 145, 3287, 68, 34.3]
]

# ================================
# ENCODING
# ================================
day_map = {'Sun':0,'Mon':1,'Tue':2,'Wed':3,'Thu':4,'Fri':5,'Sat':6}
place_map = {'Canteen':0,'Parking':1,'Class':2}
time_map = {'Mrng':0,'Noon':1,'Evng':2}

context_input = np.array([[
    place_map[input_place],
    day_map[input_day],
    time_map[input_time]
]])

# ================================
# PREDICTION
# ================================
lstm_input = np.array(last_sensor_readings).reshape(1, SEQ_LEN, 7)
lstm_features = lstm_model.predict(lstm_input, verbose=0)

hybrid_input = np.hstack([lstm_features, context_input])
prediction = xgb.predict(hybrid_input)

# ================================
# OUTPUT
# ================================
sensor_names = [
    'co_ppm', 'hum', 'mq7_raw',
    'pm1', 'pm10', 'pm25', 'temp'
]

print("\n Predicted Environmental Values:\n")
for name, value in zip(sensor_names, prediction[0]):
    print(f"{name:8s}: {value:.2f}")

import numpy as np
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# =====================================================
# 1. PREPARE TEST DATA (same logic as training)
# =====================================================
SEQ_LEN = 5

X_context = df[['place', 'day', 'time']].values
Y_true = df[['co_ppm','hum','mq7_raw','pm1','pm10','pm25','temp']].values

X_lstm_test = []
Y_test = []

for i in range(len(Y_true) - SEQ_LEN):
    X_lstm_test.append(Y_true[i:i+SEQ_LEN])
    Y_test.append(Y_true[i+SEQ_LEN])

X_lstm_test = np.array(X_lstm_test)
Y_test = np.array(Y_test)

# =====================================================
# 2. LSTM FEATURE EXTRACTION
# =====================================================
lstm_features_test = lstm_model.predict(X_lstm_test, verbose=0)

# =====================================================
# 3. HYBRID INPUT → XGBOOST
# =====================================================
X_hybrid_test = np.hstack([
    lstm_features_test,
    X_context[SEQ_LEN:]
])

Y_pred = xgb.predict(X_hybrid_test)

# =====================================================
# 4. METRICS
# =====================================================
rmse = np.sqrt(mean_squared_error(Y_test, Y_pred))
mae = mean_absolute_error(Y_test, Y_pred)
r2 = r2_score(Y_test, Y_pred)

print(" Hybrid Model Performance")
print(f"RMSE : {rmse:.3f}")
print(f"MAE  : {mae:.3f}")
print(f"R²   : {r2:.3f}")

"""CONFUSION MATRIX"""

# =====================================================
# CONFUSION MATRIX (AQI CATEGORY BASED ON PM2.5)
# =====================================================

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

# Convert PM2.5 value to AQI category
def pm25_to_aqi_category(pm):
    if pm <= 12:
        return 0   # Good
    elif pm <= 35.4:
        return 1   # Moderate
    elif pm <= 55.4:
        return 2   # Unhealthy for Sensitive
    elif pm <= 150.4:
        return 3   # Unhealthy
    elif pm <= 250.4:
        return 4   # Very Unhealthy
    else:
        return 5   # Hazardous

# Extract actual and predicted PM2.5 values
actual_pm25 = Y_test[:,5]
pred_pm25 = Y_pred[:,5]

# Convert to AQI categories
actual_classes = [pm25_to_aqi_category(x) for x in actual_pm25]
pred_classes = [pm25_to_aqi_category(x) for x in pred_pm25]

# Generate confusion matrix
cm = confusion_matrix(actual_classes, pred_classes)

# Display confusion matrix
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=[
        "Moderate",
        "Unhealthy(S)",
        "Unhealthy",
        "Very Unhealthy"
    ]
)

plt.figure(figsize=(7,6))
disp.plot(cmap="Blues")
plt.title("AQI Confusion Matrix (PM2.5 Categories)")
plt.show()

""" ACTUAL vs PREDICTED GRAPH"""

# ===============================
# ACTUAL vs PREDICTED GRAPH
# ===============================

plt.figure(figsize=(6,6))

plt.scatter(Y_test[:,5], Y_pred[:,5])

plt.xlabel("Actual PM2.5")
plt.ylabel("Predicted PM2.5")

plt.title("Actual vs Predicted PM2.5")

plt.grid(True)
plt.show()